---
- hosts: server
  tasks:

    - name:Install EPEL
      yum: name=epel-release state=present

    - name: Install nginx
      apt: pkg=nginx state=installed 
      notify:
         - start nginx

  handlers:
    - name: start nginx
      service: name=nginx state=started